### ISSUE TITLE
Allow to format html templates at buildtime and make them static (out of the box)

### ISSUE THREAD

**Issue by ia3andy** [quarkiverse/quarkus-web-bundler#130]
If a html template (e.g. `index.html` or `page1.html`) is in the `web` directory root, it will be formatted using Qute at build-time (Runtime Qute data and namespaces won't be available), `{#bundle }` will be available.
It will be generated as a static file for runtime and served at the root-path.

**Comment by phillip-kruger** [comment]
We can probably make some other things from build available in the context of the template, like application name and version ?
