### ISSUE TITLE
Dev Mode issues because of a cache in the Vertx file server

### ISSUE THREAD

**Issue by ia3andy** [quarkiverse/quarkus-web-bundler#171]
Currently, if there is not `src/main/META-INF/resources` directory, Quarkus Vertx Http is not treating the `META-INF/resources` as a dynamic content directory and enable a cache. This leads to problems:
- out of sync index.html (new bundle is generated, old index.html)
- script not getting updated on changes

The workaround is to create an empty `src/main/META-INF/resources/fixme.txt` until this gets a proper fix.

**Comment by ia3andy** [comment]
This is fixed and will be available in 1.4.0.CR1

**Comment by ppalaga** [comment]
@ia3andy could you please sketch how you solved it? I think I am suffering from the same issue in https://github.com/quarkiverse/quarkus-antora
