### ISSUE TITLE
Exclude source mapping from release build

### ISSUE THREAD

**Issue by haz00** [quarkiverse/quarkus-web-bundler#194]
Is it possible to exclude source mapping from the release build? I can see that these files are included, and all things like comments can be viewed in the release bundle.

**Comment by ia3andy** [comment]
It's not implemented yet but this is an option we could add and then that you could configure to be effective only in production for example.

**Comment by ia3andy** [comment]
https://github.com/mvnpm/esbuild-java/blob/main/src/main/java/io/mvnpm/esbuild/model/EsBuildConfigBuilder.java#L128

**Comment by ia3andy** [comment]
@haz00 I just made a PR https://github.com/quarkiverse/quarkus-web-bundler/pull/195

**Comment by haz00** [comment]
Great, thank you

**Comment by ia3andy** [comment]
I am waiting for a few new things before releasing it

**Comment by ia3andy** [comment]
@haz00 1.5.0.CR1 should soon be on central with this feature + the new dev-ui
