### ISSUE TITLE
Enable ecosystem-ci

### ISSUE THREAD

**Issue by ia3andy** [quarkiverse/quarkus-web-bundler#199]
#197 could have been catched earlier

**Comment by melloware** [comment]
All contributors PR submitted.

**Comment by melloware** [comment]
PR submitted to Ecosystem CI:https://github.com/quarkusio/quarkus-ecosystem-ci/pull/155

**Comment by melloware** [comment]
I think this can be closed.

**Comment by ia3andy** [comment]
Thanks @melloware :)
