### ISSUE TITLE
livereload not enabled unless i include a mvnnpm dependency

### ISSUE THREAD

**Issue by maxandersen** [quarkiverse/quarkus-web-bundler#227]
I have index.html with {#bundle /} but nothing else.

livereload is not included.

even tried adding app/test.js - no difference.

first when I added this to pom did livereload kick in:

```
<dependency>
        <groupId>org.mvnpm</groupId> 
        <artifactId>jquery</artifactId> 
        <version>3.7.0</version> 
        <scope>provided</scope> 
    </dependency>
```

should livereload not just work without any js added to the project?

**Comment by ia3andy** [comment]
Closing this for now as the web-bundler live-reload only gets enabled when it's used. Having live-reload for other Quarkus stuff would be great but this is another topic.
