### ISSUE TITLE
Response.seeOther doesn't work in dev mode

### ISSUE THREAD

**Issue by rpdeadly** [quarkiverse/quarkus-web-bundler#245]
Hello.
       I really like web-bundler extension's live-reload feature but I cannot get redirects to work with live-reload enabled. I'm using Quarkus version 3.12.1 and here are by dependencies.
       
       
       <dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-rest-qute</artifactId>
		</dependency>
		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-rest</artifactId>
		</dependency>
		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-rest-jsonb</artifactId>
		</dependency>
		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-rest-client-jsonb</artifactId>
		</dependency>
		
		<dependency>
			<groupId>io.quarkiverse.web-bundler</groupId>
			<artifactId>quarkus-web-bundler</artifactId>
			<version>1.6.0</version>
		</dependency>

**Comment by ia3andy** [comment]
I don't see how this can be related to the web-bundler,

**Comment by phillip-kruger** [comment]
Maybe share a reproducer.

**Comment by ia3andy** [comment]
@rpdeadly could you share a reproducer? Please re-open when you do. Thanks!
