### ISSUE TITLE
Bundler envs are not available in Playwright tests

### ISSUE THREAD

**Issue by gbourant** [quarkiverse/quarkus-web-bundler#247]
If you run the reproducer and visit `http://localhost:8080/hello/env` the `quarkus.web-bundler.bundling.envs.ENV=${quarkus.profile}` is available.

Now, if you run the test PlaywrightTest and open the DEV Tools you can see that the ENV variable is not available.

![image](https://github.com/quarkiverse/quarkus-web-bundler/assets/9791051/8de0f1d5-eca5-4037-b803-3581e40d5e93)

Reproducer: https://github.com/gbourant/qute-bugs

**Comment by ia3andy** [comment]
is it working with normal string envs?


I was thinking about adding the Quarkus Launch Mode as env by default, would that be ok?

**Comment by ia3andy** [comment]
https://github.com/quarkiverse/quarkus-web-bundler/issues/188

**Comment by gbourant** [comment]
> is it working with normal string envs?

Well yes, i tried some hard coded value and it's available.

> I was thinking about adding the Quarkus Launch Mode as env by default, would that be ok?

For my case at the moment yes, it would be enough.

**Comment by ia3andy** [comment]
This should be fixed in 1.7.0
