### ISSUE TITLE
cannot find module in tsx files

### ISSUE THREAD

**Issue by nimo23** [quarkiverse/quarkus-web-bundler#289]
I use Eclipse IDE with integrated WildWebDeveloper and “Quarkus” with “Quarkus-Web-Bunder”. I have a typescript file in

`scr/main/resources/web/app/app.tsx`

I included the `react` and `react-dom` libraries in my `pom.xml `via mvnpm and they are available when starting Quarkus development mode. 

```
...
		<dependency>
			<groupId>org.mvnpm</groupId>
			<artifactId>react</artifactId>
			<version>18.3.1</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.mvnpm</groupId>
			<artifactId>react-dom</artifactId>
			<version>18.3.1</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.mvnpm.at.types</groupId>
			<artifactId>react</artifactId>
			<version>18.3.12</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.mvnpm.at.types</groupId>
			<artifactId>react-dom</artifactId>
			<version>18.3.1</version>
			<scope>provided</scope>
		</dependency>
...
```

Everything works. However, I'm having problems with code completion because of the following issue ("Cannot find module.."):

![app-tsx](https://github.com/user-attachments/assets/3bc7c372-ee0f-4a61-b916-cffb2339573b)

I have the `tsconfig.json` in `scr/main/resources/web/tsconfig.json`:

```
{
	"compilerOptions": {
		"baseUrl": ".",
		"rootDir": ".",
		"module": "esnext",
		"target": "ES2015",
		"lib": [
			"es6",
			"dom"
		],
		"sourceMap": true,
		"jsx": "react",
		"moduleResolution": "node",
		"strict": true,
		"forceConsistentCasingInFileNames": true,
		"noImplicitReturns": true,
		"noImplicitThis": true,
		"noImplicitAny": false,
		"allowJs": true,
		"esModuleInterop": true,
		"allowSyntheticDefaultImports": true,
		"paths": {
			"@app/*": [
				"src/app/*"
			],
			"@assets/*": [
			]
		},
		"importHelpers": true,
		"skipLibCheck": true
	},
	"include": [
		"**/*.ts",
		"**/*.tsx",
		"**/*.jsx",
		"**/*.js"
	],
	"exclude": [
		"node_modules"
	]
}
```

 As “react” and “react-dom” are in a java archive, I don’t know how to make it “visible” to tsconfig.

**Is there a way to resolve the "Cannot find module.."-issue?**

**Comment by ia3andy** [comment]
ok can you try this:
application.properties
```
quarkus.web-bundler.dependencies.node-modules=node_modules
```


then resinstall, make sure to add node_modules to the git ignore

**Comment by ia3andy** [comment]
Also all deps should be provided
