### ISSUE TITLE
support adding/maintaining dependencies with user defined node_modules

### ISSUE THREAD

**Issue by nimo23** [quarkiverse/quarkus-web-bundler#290]
Currently `quarkus-web-bundler` allows adding dependencies through either `mvnpm` or `webjars`. 

Please provide another option by using `npm` directly i.e. the user should be able to add a dependency through `npm install`. Maybe it can work like this:

Add a new config in application.properties, e.g.:

1. option:
```
// scans the node_modules directory 
// provided by the user in the given directory
quarkus.web-bundler.dependencies.external.node-modules
=web/app/node_modules
```

2. option:
```
// When quarkus-web-bundler creates its package.json, 
// it also merges the user-supplied package.json dependencies,
// e.g. only the content of "dependencies" and "save-dependencies" are merged":
quarkus.web-bundler.dependencies.external.package-json
=web/app/package.json
```

**Comment by ia3andy** [comment]
What would you benefit from using npm directly? I think if you need this, you should use Quinoa
