### ISSUE TITLE
Check IDEs Quarkus tooling support for this

### ISSUE THREAD

**Issue by ia3andy** [quarkiverse/quarkus-web-bundler#4]
Make sure the Quarkus tooling support this and the tooling team is aware of this.

**Comment by maxandersen** [comment]
or at least check that there aren't parts of it that is inherently difficult to tool :)

**Comment by ia3andy** [comment]
Having the node_modules dir as part of the root of the project allow to have IDE support:
https://docs.quarkiverse.io/quarkus-web-bundler/dev/advanced-guides.html#node_modules
