### ISSUE TITLE
Import scss from Web Dependencies

### ISSUE THREAD

**Issue by ia3andy** [quarkiverse/quarkus-web-bundler#58]
It is currently not possible to import scss from Web Dependencies. 

Because it is not available in esbuild CLI, scss conversion is done by the web bundled as a pre-step of bundling on all project scss files. In order to support importing scss from Web Dependencies, a solution would be to detect import and convert the given scss (it would require a lot of file processing).

You may upvote this if you feel this is really needed.

**Comment by ia3andy** [comment]
This is now working starting from 1.3.0!

**Comment by PraveenGandhi** [comment]
Hi @ia3andy 

It is not working forn me, could you please let me know if I need to configure anything for importing the scss files from web dependencies like bootstrap **(org.mvnpm:bootstrap:5.3.2)**
