### ISSUE TITLE
DevUI: Add Support

### ISSUE THREAD

**Issue by melloware** [quarkiverse/quarkus-web-bundler#63]
Similar to how we do it in Quinoa.

**Comment by ia3andy** [comment]
Here are some ideas:
- Bundled directories list
- What's served by the web bundler
- Latest generated mapping
- List of dependencies (and maybe what could be imported)

**Comment by melloware** [comment]
I will get it started since I am not as familiar with this code base and then we can keep adding on to it.

**Comment by FroMage** [comment]
Isn't it called Dev UI? Dev Console is the terminal bit :)

**Comment by melloware** [comment]
I knew what he meant 😄
